import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, CalendarDays, Check, MapPin, Menu, Search, ShieldCheck, Sparkles, Star } from "lucide-react";
import s from "./demo.module.css";
const demos:Record<string,any>={
"velocity-black":{brand:"V/BLACK",type:"rent",theme:"velocity",eyebrow:"PREMIUM MOBILITY",title:"Yolculuğunuz,\nstandartların üzerinde.",text:"Seçkin araç filosu, kusursuz rezervasyon deneyimi ve ayrıcalıklı hizmet.",cta:"Aracını seç",stats:[["120+","Premium araç"],["7/24","Concierge"],["18","Lokasyon"]]},
"moda-atelier":{brand:"ATELIER",type:"shop",theme:"atelier",eyebrow:"NEW SEASON / 2026",title:"Sessiz lüksün\nyeni formu.",text:"Güçlü siluetler, doğal dokular ve zamansız parçalarla hazırlanan yeni koleksiyon.",cta:"Koleksiyonu keşfet",stats:[["01","Editorial"],["02","Collection"],["03","Stories"]]},
"estate-prime":{brand:"PRIME",type:"estate",theme:"estate",eyebrow:"EXCEPTIONAL PROPERTIES",title:"Yaşamınıza değer\nkatan adresler.",text:"Şehrin seçkin lokasyonlarında uzman danışmanlığıyla benzersiz gayrimenkuller.",cta:"İlanları keşfet",stats:[["240+","Seçkin portföy"],["34","Uzman"],["12","Şehir"]]},
"noir-table":{brand:"NOIR",type:"food",theme:"noir",eyebrow:"A TASTE BEYOND",title:"Her tabakta\nyeni bir hikâye.",text:"Yerel malzemeler, çağdaş teknikler ve gecenin ritmiyle şekillenen gastronomi deneyimi.",cta:"Masa ayırt",stats:[["7 Course","Tasting menu"],["19:00","Dinner"],["Istanbul","Bosphorus"]]},
"azure-stay":{brand:"AZURE",type:"hotel",theme:"azure",eyebrow:"AEGEAN ESCAPE",title:"Zamanın yavaşladığı\nyerde uyanın.",text:"Ege'nin sakin kıyısında doğayla bütünleşen odalar ve kişiselleştirilmiş deneyimler.",cta:"Konaklamanı planla",stats:[["24","Özel süit"],["2","Infinity pool"],["1","Unutulmaz kaçış"]]},
"clarity-clinic":{brand:"CLARITY",type:"clinic",theme:"clarity",eyebrow:"SCIENCE. CARE. YOU.",title:"Sağlığınız için\nnet bir yaklaşım.",text:"Alanında uzman hekimler, ileri teknoloji ve insan odaklı bütünsel sağlık hizmeti.",cta:"Randevu oluştur",stats:[["18","Uzman hekim"],["12K+","Danışan"],["4.9","Memnuniyet"]]},
"monolith-studio":{brand:"MONOLITH®",type:"corp",theme:"monolith",eyebrow:"WE BUILD BOLD IDEAS",title:"Büyük fikirler.\nNet sonuçlar.",text:"Markaları strateji, tasarım ve teknolojiyle sektörlerinin önüne taşıyan bağımsız stüdyo.",cta:"Birlikte çalışalım",stats:[["48","Global proje"],["11","Ödül"],["9","Ülke"]]},
"nexa-commerce":{brand:"NEXA",type:"shop",theme:"nexa",eyebrow:"EVERYDAY, ELEVATED",title:"Yeni nesil alışveriş,\ntam sana göre.",text:"Trend ürünler, hızlı teslimat ve kişiselleştirilmiş keşif deneyimi tek platformda.",cta:"Alışverişe başla",stats:[["50K+","Ürün"],["24h","Hızlı kargo"],["4.8","Müşteri puanı"]]},
"drive-electric":{brand:"DRIVE:E",type:"rent",theme:"electric",eyebrow:"THE FUTURE MOVES",title:"Sessiz. Güçlü.\nTamamen elektrikli.",text:"Şehir içi yolculuğu akıllı teknoloji ve sıfır emisyonla yeniden tanımlayın.",cta:"Sürüşünü başlat",stats:[["520 km","Menzil"],["18 dk","Hızlı şarj"],["0","Emisyon"]]}};
export default function DemoPage({params}:{params:{slug:string}}){const d=demos[params.slug];if(!d)notFound();return <main className={`${s.demo} ${s[d.theme]}`}><div className={s.topNotice}><Link href="/"><ArrowLeft/> Tasarımlara dön</Link><span>Canlı demo • {d.brand}</span><Link href="/iletisim">Bu tasarımı iste <ArrowRight/></Link></div><header className={s.header}><b>{d.brand}</b><nav><a>Keşfet</a><a>Hizmetler</a><a>Hakkımızda</a><a>İletişim</a></nav><div><Search/><Menu/></div></header><section className={s.hero}><div className={s.orb}/><div className={s.copy}><span><Sparkles/> {d.eyebrow}</span><h1>{d.title.split("\n").map((x:string,i:number)=><span key={x}>{x}{i===0&&<br/>}</span>)}</h1><p>{d.text}</p><button>{d.cta}<ArrowRight/></button></div><div className={s.art}><div className={s.artFrame}><div className={s.artNav}><i/><i/><i/></div><div className={s.artSubject}>{d.type==="rent"?"GT":d.type==="estate"?"VILLA":d.type==="food"?"CHEF":d.type==="hotel"?"SUITE":d.type==="clinic"?"CARE":d.type==="corp"?"A—01":"DROP 01"}</div><div className={s.artLines}><i/><i/><i/></div></div></div></section><section className={s.stats}>{d.stats.map((x:string[])=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</section><section className={s.features}><article><span>01</span><h2>Akıllı kullanıcı deneyimi</h2><p>Her ayrıntısı kullanıcı yolculuğuna göre tasarlanmış güçlü ve akıcı deneyim.</p><Check/></article><article><span>02</span><h2>Premium hizmet</h2><p>Güven veren içerik mimarisi, hızlı etkileşim ve yüksek dönüşüm odağı.</p><ShieldCheck/></article><article><span>03</span><h2>Her ekranda etkileyici</h2><p>Mobil, tablet ve masaüstünde karakterini koruyan kusursuz tasarım sistemi.</p><Star/></article></section><section className={s.demoCta}><span><CalendarDays/> Projenizi hayata geçirelim</span><h2>Bu tasarımı markanıza<br/>özel uyarlayalım.</h2><Link href="/iletisim">Teklif alın <ArrowRight/></Link></section><footer className={s.footer}><b>{d.brand}</b><span>Demo experience by Dromocob Studio</span><span><MapPin/> İstanbul · Türkiye</span></footer></main>}
export function generateStaticParams(){return Object.keys(demos).map(slug=>({slug}))}
