const products = [
  ["Form Masa Lambası", "Yaşam", "3.490 TL", "coral", "01"],
  ["Outline Sırt Çantası", "Aksesuar", "2.850 TL", "blue", "02"],
  ["Sunday Seramik Set", "Ev", "1.975 TL", "sand", "03"],
  ["Loop Kablosuz Hoparlör", "Teknoloji", "4.290 TL", "lime", "04"],
];

export default function Home() {
  return <main>
    <div className="announcement">Türkiye'nin her yerine ücretsiz teslimat · 30 gün kolay iade</div>
    <header className="header shell"><a className="brand" href="#">DROMOCOB<sup>®</sup></a><nav><a href="#koleksiyon">Yeni gelenler</a><a href="#koleksiyon">Ev & yaşam</a><a href="#koleksiyon">Aksesuar</a><a href="#koleksiyon">Teknoloji</a></nav><div className="actions"><button aria-label="Ara">⌕</button><button className="bag">Sepet <b>0</b></button></div></header>
    <section className="hero shell"><div className="heroCopy"><span className="kicker">YENİ SEZON · 2026</span><h1>İyi tasarım,<br/><em>günlük hayat</em> için.</h1><p>Özenle seçilmiş objeler, aksesuarlar ve teknoloji ürünleri. Sade, işlevsel ve uzun ömürlü.</p><div className="buttons"><a className="primary" href="#koleksiyon">Koleksiyonu keşfet ↗</a><a href="#hikaye">Hikâyemiz →</a></div></div><div className="heroArt"><div className="orb one"/><div className="orb two"/><div className="object"><span>D</span></div><div className="note"><small>SEÇKİ 01</small><strong>Gündelik<br/>ikonlar.</strong></div></div></section>
    <section className="proof shell"><div><b>01</b><span><strong>Seçilmiş ürünler</strong><small>Kalite ve tasarım odaklı seçki</small></span></div><div><b>02</b><span><strong>Güvenli ödeme</strong><small>Korunan, hızlı ödeme deneyimi</small></span></div><div><b>03</b><span><strong>Hızlı teslimat</strong><small>Siparişe anlık takip desteği</small></span></div></section>
    <section className="collection shell" id="koleksiyon"><div className="sectionHead"><div><span className="kicker">EDİTÖRÜN SEÇİMİ</span><h2>Şu an sevdiğimiz ürünler.</h2></div><a href="#">Tümünü gör ↗</a></div><div className="grid">{products.map(([name,category,price,tone,no])=><article key={name}><div className={`visual ${tone}`}><span>{no}</span><div className="shape"/><button aria-label="Favorilere ekle">♡</button></div><div className="info"><div><small>{category}</small><h3>{name}</h3></div><strong>{price}</strong></div></article>)}</div></section>
    <section className="story shell" id="hikaye"><div className="storyVisual"><span>FORM<br/>FOLLOWS<br/><i>FEELING</i></span></div><div className="storyCopy"><span className="kicker">BİZİM YAKLAŞIMIMIZ</span><h2>Daha az eşya.<br/>Daha iyi seçimler.</h2><p>Geçici trendler yerine iyi düşünülmüş tasarımları seçiyoruz. Her ürünün bir işlevi, her detayın bir nedeni var.</p><a className="primary light" href="#">Dromocob'u tanıyın ↗</a></div></section>
    <section className="newsletter shell"><div><span className="kicker">DROMOCOB NOTLARI</span><h2>Yeniliklerden<br/>ilk sizin haberiniz olsun.</h2></div><form><label htmlFor="email">E-posta adresiniz</label><div><input id="email" type="email" placeholder="ornek@eposta.com"/><button type="submit">Kaydol →</button></div><small>Kaydolarak iletişim ve gizlilik koşullarını kabul etmiş olursunuz.</small></form></section>
    <footer><div className="shell footerTop"><a className="brand" href="#">DROMOCOB®</a><div><strong>Alışveriş</strong><a href="#koleksiyon">Yeni gelenler</a><a href="#koleksiyon">Koleksiyonlar</a><a href="#koleksiyon">Hediye seçkisi</a></div><div><strong>Yardım</strong><a href="#">Teslimat & iade</a><a href="#">Sıkça sorulanlar</a><a href="#">İletişim</a></div><div><strong>Sosyal</strong><a href="#">Instagram ↗</a><a href="#">Pinterest ↗</a></div></div><div className="shell footerBottom"><span>© 2026 Dromocob Demo Store</span><span>Sunum amaçlı demo çalışmasıdır.</span></div></footer>
  </main>;
}
